language: bash
script:
  - sed -i -e "2i var CACHE_NAME = \'grandcolline-cache-v$TRAVIS_BUILD_NUMBER\';" ./sw.js
  - MANIFEST=$(cat manifest.json | jq -c .)
  - echo $MANIFEST > manifest.json
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  endpoint: "$AWS_S3_ENDPOINT"
  region: "$AWS_REGION"
  bucket: "$AWS_S3_BUCKET"
  local-dir: .
  acl: public_read
  skip_cleanup: true
  on:
    repo: grandcolline/grandcolline.com
branches:
  only:
  - master

