branches:
  only:
  - master
language: node_js
node_js:
  - 7
install:
- yarn
script: sed -i -e "2i var CACHE_NAME = \'grandcolline-cache-v$TRAVIS_BUILD_NUMBER\';" ./sw.js
script:
- yarn run lint
- yarn run build
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$AWS_S3_BUCKET"
  region: "$AWS_REGION"
  acl: public_read
