script: echo "do nothing"
deploy:
  provider: s3
  access_key_id:
    secure: pHJ2rTOv5s4LoIK+qiwGx0VvSt1W3fMbzHtqSoSKneCLkBUsD+GeD4+B2lZ32V4fBMBYQdJi+ivQo9wHiEIUBWUUcPSb0mKUzi39Q7Jq3VWkDY/l1ie/RdGZGnJpRS1JoaBfLUmeTCjkLyCmNexgSnAGB5HWaigmSg4yg3rJMYWr2LqNxTzifHG677B3EVgceUohC/kfnYO0mL+ubWvh2sh4YG1bL0OG80dckGlkCutTWzxftZiGAWZJ7RR1HdgSqkdJRY27UtXnkWBwgacc78fVcIv8xPR8tUGZjexGnl0jA6NS60WfN29kwOSyKG+VqasABJ1rAzcw3QIpneM1qNgBdryydC4fjfA+pa/LOsmuXIc8edF5IBaZquOISEuC6q4CqbevYdLttSrw7GWOcw6v+D+mTrjtwenLLK2EYTTKzc1ZYL0vwEwDbpX2MW8Xa/VPVeh/vZTl1kG3b94ESQlCJhXUH6kXhJeV3MM0iwdpf9EnS9/INfNUYkPG5S+0uwUinAzvYCgHV43xu3bN4vSfuFhVeAMXDDiaU6oYQ9jnFp1eIU3QPAVImCefqNtC24y0N/QUnBXwEzWcjkg2AC6Nl4myJGQw3Eh47dkwVCJ8Rs8NTxGRFNyBJGuLPFPtZoEb3zrIf2rGtWV0iVYJCfD2jnvtT2lY3U4H/wkOvro=
  secret_access_key:
    secure: HjrfjsxSODQwOZ/Hi5ioE+TErFRktVF3FDcKYFgP51HRPXdQx5Ui4b3bvIYfZHFFe+6fu21IkVazAeKr/zfKaiA6HNXk3V3wM4ph8THHoFF7NLh66mUZALTJ57D7m4xAwUkDGS/pWVs6UYtoHIFrhxi/QtX1qmey4I0rgM39FxxTckCq4ChZCC6ogI09QRCOIna85Rn73OGFBfTp6DBebwrWCb5v/6egnfpXwIKut0F58a0QnA7PafGnLn0oqC3vJQKMfNPiiL9JJZHCPR9Wq65E5GdfRgsyJF3b23JvOMpSmN4cPyXFcHvtJTcXBblpiZaYL/boNPJmzcFY4qEIWgCZvkBtlOWbfZ4Tr+9CJoSa7UEmmDCSX9xf1CvOHxUm5wE2ZzDRhEHgx5PUnCtDNERqBbBjXv7kkfEeph9vPAQ4VbIpoPYrlTyk1/eMOlxFx11N/qCr/oDse92Phhh+NX5ExYJsj5BCZMcWfRzaMaDahbpPgQrUxjFnQaaIz+4nsxZbohfm6Kjh44l0mOi/naRNeo38TBsDEZOXiLrde1UHY/uW1G5GX4pJds01GpZtoU60AqVn6K7hvAeyTN9v50whhuYtpuPfzzFFJjk2XUoyb1ToBtv2htLXbGpIepxVWtYSSGPLRyfHNSu/ujwpZnPoKjb8Eu47i0Ck9hgyJiY=
  bucket: grandcolline.com
  endpoint: http://grandcolline.com.s3-website-ap-northeast-1.amazonaws.com
  region: ap-northeast-1
  skip_cleanup: true
  on: 
    branch: master
