language: python
python:
  - "3.5"
cache: pip
install:
  - pip install awscli
script: echo "do nothing"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET
  endpoint: $AWS_S3_ENDPOINT
  region: $AWS_REGION
  skip_cleanup: true
  on: 
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
