name: Deploy Production
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Deploy to Production
        uses: cloudflare/wrangler-action@v3
        with:
          # CLOUDFLARE_ACCOUNT_ID
          #  - Cloudflare ダッシュボード > Workers & Pages > Overview で確認
          #  - 右側のサイドバーに表示されています
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # CLOUDFLARE_API_TOKEN
          #  - Cloudflare ダッシュボード > My Profile > API Tokens で作成
          #  - 必要な権限: "Cloudflare Workers Scripts:Edit"
          #  - Account リソースへのアクセスも必要
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy
